### ISSUE TITLE
Use of AnyService seems causes osgi.service capability

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#5750]
With bnd 6.4.0 I always get osgi.service;filter:="(objectClass=org.osgi.service.component.AnyService)";effective:=active, which does not really made sense. I think there should be no service requirement for such a case.

I could not test it in a different WS and a newer bnd version yet.

**Comment by pkriens** [comment]
@amitjoy didn't you make a change here?

**Comment by amitjoy** [comment]
This has been fixed immediately by @bjhargrave as soon as I reported it. Here is the MR: https://github.com/bndtools/bnd/pull/5704

**Comment by juergen-albert** [comment]
Okay, thanks heaps. I will recheck with the latest bnd version and will close the issue. Sorry to bother you.

**Comment by juergen-albert** [comment]
Well, this is still an issue. @bjhargrave has fixed, that no Capability is added if somebody would register an AnyService (Why every somebody would do this. If a Services references something using AnyService, it still adds a Requirement for AnyService

```
Require-Capability: osgi.service;filter:="(objectClass=org.osgi.service.component.AnyService)";effective:=active
```
